debug: true

server:
  #address: 192.168.0.49
  port: 8080
  servlet:
    context-path: /sysmat3

http:
    end-point: /sysmat3 
    
management:
   endpoints:
      web:
         exposure:
            include: info, health , mappings , caches , conditions , metrics , configprops , env , info , integrationgraph

application:
   baseUrl: sysmat
            
spring:
  application:
    name: sysmat
  datasource:
    jdbcUrl: jdbc:postgresql://127.0.0.1:5432/connemat_template?schema=master
    url: jdbc:postgresql://127.0.0.1:5432/connemat_template?schema=master
    username: postgres 
    password: postgres123
  #hikari:
    #connectionTimeout: 30000
    #maximumPoolSize: 250
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        ddl-auto: none 
#create-drop    
  #security:
    #oauth2: 
      #client:
        #clientId: sysmat 
        #clientSecret: 16fc98ff-c87b-45e1-9a2b-3d87bb3d71a6
        #accessTokenUri: http://127.0.0.1:4200/auth/realms/connemat/protocol/openid-connect/token
        #userAuthorizationUri: http://127.0.0.1:4200/auth/realms/connemat/protocol/openid-connect/auth
        #authenticationScheme: header
        #clientAuthenticationScheme: header 
      #resource:
        #userInfoUri: http://127.0.0.1:4200/auth/realms/connemat/protocol/openid-connect/userinfo
      #resourceserver:  
        #token-info-uri: http://localhost:8180/auth/realms/sysmat/protocol/openid-connect/token/introspect
        #jwt.issuer-uri: http://127.0.0.1:4200/auth/realms/connemat
        #jwk-set-uri: http://127.0.0.1:4200/auth/realms/connemat/protocol/openid-connect/certs 
      #resourceserver: 
      #  jwt.issuer-uri: http://localhost:8180/auth/realms/sysmat
      #  jwk-set-uri: http://localhost:8080/auth/realms/sysmat/protocol/openid-connect/certs
        
keycloak: 
  realm: connemat
  auth-server-url: http://127.0.0.1:4200/auth
  verify-token-audience: true
  use-resource-role-mappings: true
  confidential-port: 0
  ssl-required: external
  resource: sysmat
  credentials: 
    secret: 16fc98ff-c87b-45e1-9a2b-3d87bb3d71a6
  bearer-only: false        
  
sysmat-realm-admin:
  userName: sysmat-admin
  password: temp123
  clientId: admin-cli 
  redirectUrl: http://127.0.0.1:4200/
  
keycloak-server-urls:
  token-url: /realms/connemat/protocol/openid-connect/token
  group-url: /admin/realms/connemat/groups
  user-url: /admin/realms/connemat/users
  logout-url: /realms/connemat/protocol/openid-connect/logout
  realm-client-url: /admin/realms/connemat/clients/ 
  resource-url: /authz/resource-server/resource
  permissions-url: /permissions
  permission-url: /authz/resource-server/permission

keycloak-config:
  datasource:
    jdbcUrl: jdbc:postgresql://127.0.0.1:5432/keycloak
    username: postgres 
    password: postgres123    
  
sysmatdefault:
  datasource:
    jdbcUrl: jdbc:postgresql://127.0.0.1:5432/sysmat3_teste?currentSchema=sysmat3
    url: jdbc:postgresql://127.0.0.1:5432/sysmat3_teste?currentSchema=sysmat3
    username: postgres 
    password: postgres123    
    pool-size: 30
    
#jwkCertsUri: http://127.0.0.1:8180/auth/realms/connemat/protocol/openid-connect/certs